[package]
name = "palette"
version = "0.0.0"
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]
license = "MIT OR Apache-2.0"

[features]
strict = []

[dev-dependencies]
image = "0.4"
approx = "0.1"
clap = "1"
