[package]
name = "palette"
version = "0.4.1" #automatically updated
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]
exclude = ["scripts/*", "examples/*", "tests/*", "res/*", ".travis.yml", ".gitignore", "CHANGELOG.md", "CONTRIBUTING.md", "version.sh"]
description = "Makes linear color calculations and conversion easy and accessible for anyone."
documentation = "https://docs.rs/palette/0.4.1/palette/"
repository = "https://github.com/Ogeon/palette"
readme = "README.md"
keywords = ["color", "colour", "space", "linear"]
license = "MIT OR Apache-2.0"

build = "build/main.rs"

[features]
default = ["named_from_str", "std"]
named_from_str = ["named", "phf", "phf_codegen", "std"]
named = []
serializing = ["serde", "std"]

#ignore in feature test
std = ["approx/std", "num-traits/std"]
strict = [] # Only for CI internal testing

[dependencies]
palette_derive = {version = "0.4.1", path = "../palette_derive"}
num-traits = {version = "0.2", default-features = false}
approx = {version = "0.3", default-features = false}

[dependencies.libm]
version = "0.1"
optional = true

[dependencies.phf]
version = "0.7"
optional = true

[dependencies.serde]
version = "1"
features = ["serde_derive"]
optional = true

[dev-dependencies]
image = "0.21"
clap = "2"
csv = "1"
serde = "1"
serde_derive = "1"
lazy_static = "1"
serde_json = "1"

[build-dependencies.phf_codegen]
version = "0.7"
optional = true
