on:
  push:
    branches:
      - master

name: Publish documentation

jobs:
  documentation:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Generate
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --package palette --no-deps
      - name: Upload
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: target/doc
