on: [pull_request]
name: Benchmark pull requests
jobs:
  runBenchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch master
        run: git fetch --prune origin master
      - name: Run benchmark
        uses: matchai/criterion-compare-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_TARGET_DIR: ${{ format('{0}/target', github.workspace) }}
